# Generated by Django 4.2.3 on 2023-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_rename_menu_menuitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="no_of_guest",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="inventory",
            field=models.IntegerField(),
        ),
    ]
